### ISSUE TITLE
Last item on the right

### ISSUE THREAD

**Issue by Gilles-L-Artaban** [gustavoconci/bootstrap.masonry.js#2]
Hello there !

Thank you for this plugin.

We noticed something annoying. The last item is on the right side even thought there is space on the left side...
Is it possible to do something to make it otherwise ?

Thank you !

**Comment by gustavoconci** [comment]
Hi!

I will review the code.
I noticed now that the examples are no longer working. I'll put the examples in Codepen and let you know.

Thanks!

**Comment by gustavoconci** [comment]
Examples updated:

Masonry Bootstrap 4: http://conci.com.br/masonry/bootstrap4.html
Masonry Bootstrap 3: http://conci.com.br/masonry/bootstrap3.html
